dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-8
      - g++-8

install:
  - export CC="gcc-8"
  - export CXX="g++-8"
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version

before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..
  - git clone https://github.com/nathrick/platercg.git
  - cd platercg
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build

script:
  - cmake ..
  - make



